# Initial settings for this application
server:
  servlet:
    context-path: /pointrecord
  port: 8080

# Settings spring
spring:
  application:
    name: pointrecord
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

# Settings for the log system
logging:
    file: ${spring.application.name}.log
    level:
      org:
        hibernate:
          SQL: DEBUG
        springframework:
          cloud: DEBUG
